#!/usr/bin/env bash
#
# Cdist initial manifest

# Break on errors
set -e

MANIFESTALL="autorun"
SOURCESTACK=()
SOURCESTACKONCE=()

cdist_source() {
   local man="$1"
   if [[ "${CDISTDEBUG:-0}" -gt 0 ]]; then
      echo "INIT MANIFEST: sourcing $man"
      set -x
   fi
   . "$man"
   if [[ "${CDISTDEBUG:-0}" -gt 0 ]]; then
      set +x
      echo "INIT MANIFEST: done sourcing $man"
   fi
}

# Safe include function for manifests including other manifests
include() {
   local i dir include_manifest=''
   local target="$1"
   local run_type="${2:-}"
   local current_manifest="${BASH_SOURCE[1]:-unknown}"

   if [[ -z "${CDISTACTION:-}" && -e "${__manifest}/${MANIFESTALL}/${target}" ]]; then
      return 0
   fi

   if [[ "${target##*/}" == "${__cdist_manifest##*/}" ]]; then
      echo "ERROR: The init manifest itself cannot be included" >&2
      exit 1
   fi

   if [[ -e "${__manifest}/${target}" ]]; then
      include_manifest="${__manifest}/${target}"
   else
      for dir in "${__manifest}"/*/ ; do
         if [[ -e "${dir}${target}" ]]; then
            include_manifest="${dir}${target}"
            break
         fi
      done
   fi

   if [[ "${run_type}" == "once" ]]; then
      for i in "${SOURCESTACKONCE[@]:-}"; do
         if [[ "${i}" == "${include_manifest}" ]]; then
            return 0
         fi
      done
   fi

   # Reset SOURCESTACK when this function is called from a new manifest
   if [[ ! " ${SOURCESTACK[*]:-} " =~ " ${current_manifest} " ]]; then
      SOURCESTACK=("${current_manifest}")
   fi

   for i in "${SOURCESTACK[@]:-}"; do
      if [[ "${i}" == "${include_manifest}" ]]; then
         read -r line func file < <(caller)
         [[ -z "${file:-}" ]] && file="${func}"
         file="${file##*/}"
         echo "ERROR: Circular/multiple include(s) of ${target} in manifest ${file}" >&2
         exit 1
      fi
   done

   if [[ -n "${include_manifest}" ]]; then
      SOURCESTACK+=("${include_manifest}")
      if [[ "${run_type}" == "once" ]]; then
         SOURCESTACKONCE+=("${include_manifest}")
      fi
      cdist_source "$include_manifest"
   else
      return 1
   fi
}

# Safe include function for manifests including other manifests, once per host
include_once() {
   include "${1}" once
   return $?
}

# Parse configuration file
include_cfg() {
   local repo="$1"; shift
   local key="$1"; shift
   local line

   # Find configuration file
   include_find_cfg() {
      local i key init=0
      if [[ "$1" == "--init" ]]; then
         init=1
         shift
      fi
      key="$1"
      for i in "${!_includedirs[@]}"; do
         if [[ -f "${_includedirs[$i]}/${key}" ]]; then
            _cfgfile="${_includedirs[$i]}/${key}"; break
         fi
         [[ "$init" -eq 1 ]] && unset '_includedirs[i]'
      done
      [[ "$init" -eq 1 ]] && unset '_includedirs[i]'
      [[ -z "${_cfgfile:-}" ]] && return 1
      return 0
   }

   if [[ "${#FUNCNAME[@]}" -gt 10 ]]; then
      echo "Include depth too great." >&2
      return 1
   fi

   unset _cfgfile
   if [[ "${FUNCNAME[0]}" != "${FUNCNAME[1]:-}" ]]; then
      _includedirs=( "$@" )
      include_find_cfg --init "$key"
   else
      include_find_cfg "$key"
   fi
   [[ $? -ne 0 ]] && return

   while read -r -u 5 line; do
      key="${line:1}"
      case "${line:0:1}" in
         @) include_cfg "$repo" "$key" || { echo "Error processing include $key" >&2; return 1; }
         ;;
         !) if [[ -f "${repo}/${line:1}" ]]; then
               echo "${line:1}"
            else
               echo "File $line does not exist (from $_cfgfile)" >&2
               return 1
            fi
         ;;
      esac
   done 5< "${_cfgfile:-/dev/null}"
   return 0
}

# Pull explorer information into environment
for explorerfile in "$__global"/explorer/*; do
   [[ -e "$explorerfile" ]] || continue
   explorer="${explorerfile##*/}"
   explorer="${explorer//-/_}"

   if [[ "$(wc -l < "$explorerfile")" -eq 1 ]]; then
      declare "e_$explorer=$(< "$explorerfile")"
   else
      readarray -t "e_$explorer" < "$explorerfile"
   fi
done

# Always need fqdn to be set
if [[ -z "${e_fqdn:-}" ]]; then
   echo "fqdn not set, aborting." >&2
   exit 1
fi

if [[ "$e_fqdn" == "${e_fqdn%%.*}" ]]; then
   echo "fqdn is not fully qualified, aborting." >&2
   exit 1
fi

# Set all tags to 0
for tag in $(cdist inventory list | sed -n "s/.* //; s/,/\n/gp" | sort -u); do
   tag="${tag//-/_}"
   declare "t_$tag=0"
done

# Set host tags to 1
for tag in $(cdist inventory list "$e_fqdn" | sed -n "s/.* //; s/,/ /gp" ); do
   tag="${tag//-/_}"
   declare "t_$tag=1"
done

# Save explorer output safely
rm -rf "${CDIST_EXPLORE:?}/$e_fqdn"
mkdir -p "$CDIST_EXPLORE/$e_fqdn"
for name in "$__global"/explorer/*; do
   [[ -e "$name" ]] || continue
   cp "$name" "$CDIST_EXPLORE/$e_fqdn"
done

# Run specific manifest(s) if required. "none" will only explore.
if [[ -n "${CDISTACTION:-}" ]]; then
   [[ "$CDISTACTION" == "none" ]] && exit 0
   for manifest in ${CDISTACTION//,/ }; do
      if [[ -f "$__manifest/$manifest" ]]; then
         cdist_source "$__manifest/$manifest"
      elif [[ -f "$__manifest/$MANIFESTALL/$manifest" ]]; then
         cdist_source "$__manifest/$MANIFESTALL/$manifest"
      else
         echo "Manifest $manifest not found." >&2
         exit 1
      fi
   done
   exit 0
fi

for manifest in "$__manifest"/"$MANIFESTALL"/*; do
   [[ -e "$manifest" ]] || continue
   cdist_source "$manifest"
done
